# Generated by Django 4.2.6 on 2023-10-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
