# Generated by Django 4.2.6 on 2023-11-02 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
        ('opening', '0002_alter_opening_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
    ]
