# Generated by Django 4.2.6 on 2023-11-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
