# Generated by Django 4.2.6 on 2023-12-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogs_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='slug',
        ),
    ]
