# Generated by Django 4.2.6 on 2023-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrer',
            name='files',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
